export const ROLES = ['EMPLOYEE', 'HR_MANAGER', 'HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'];
export const ROLE_LABEL = {
  EMPLOYEE: 'Employee',
  HR_MANAGER: 'Hr Manager',
  HR_PAYROLL_USER: 'Hr Payroll User',
  HR_PAYROLL_MANAGER: 'Hr Payroll Admin',
  ADMIN: 'Admin',
};
export const EMPLOYEE_TYPES = ['FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN'];
export const EMPLOYEE_STATUS = ['ACTIVE', 'ON_LEAVE', 'TERMINATED', 'SUSPENDED'];
export const CONTRACT_STATUS = ['DRAFT', 'RUNNING', 'TERMINATED', 'EXPIRED'];
export const ATTENDANCE_STATUS = ['PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'ON_LEAVE', 'HOLIDAY', 'OVERTIME'];
export const REQUEST_STATUS = ['DRAFT', 'TO_APPROVE', 'APPROVED', 'REFUSED', 'CANCELLED'];
export const RULE_CATEGORY = ['BASIC', 'ALLOWANCE', 'REIMBURSEMENT', 'DEDUCTION', 'GROSS', 'NET'];
export const LINE_KIND = ['EARNING', 'DEDUCTION', 'ADJUSTMENT', 'REPORT'];
export const COMPUTATION_TYPE = ['FIXED', 'PERCENTAGE', 'FORMULA'];
export const PAY_FREQUENCY = ['MONTHLY', 'HALF_MONTH_FIRST', 'HALF_MONTH_SECOND', 'BI_MONTHLY', 'WEEKLY', 'CUSTOM'];
export const COMPUTE_MODE = ['PRO_RATA', 'ADVANCE_50'];
export const PAYRUN_STATUS = ['DRAFT', 'COMPUTED', 'VALIDATED', 'PAID', 'VOID'];
export const PAYSLIP_KIND = ['MONTHLY', 'HALF_FIRST', 'HALF_SECOND', 'CUSTOM', 'ARREAR', 'BONUS', 'FULL_FINAL'];
export const APPROVAL_ROUTE = ['NONE', 'MANAGER', 'HR', 'PAYROLL_OFFICER'];
